### ISSUE TITLE
emsd feature files for fold 1, 2 and 3

### ISSUE THREAD

**Issue by xixixi-7** [EIHW/motilitAI#1]

**Comment by xixixi-7** [comment]
Hello author, sorry to bother you, I have some questions to ask. In the code you provided, where are "features_fold_1", "features_fold_2" and "features_fold_3" generated, and if possible, can you provide a boilerplate format of "emsd feature files for fold 1, 2 and 3" for these files ? thank you very much.

**Comment by mauricege** [comment]
Hello,

sorry for the delayed response.

We have uploaded our extracted [feature vectors](https://mediastore.rz.uni-augsburg.de/get/U2aeGSqu_Z/
). We will not add them to the main page, as we are currently working on improving the pre-processing and feature extraction pipeline and will update the corresponding code in the repository.

Best wishes,
Maurice

**Comment by mauricege** [comment]
We have added the feature extraction pipeline with commit 6e8f76f6e95d1c06db3916573204566fdac193ab
